
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 10858;
const int acc_off_y = 18932;
const int acc_off_z = 10454;
const float acc_scale_x = 14490.968700;
const float acc_scale_y = 18901.630567;
const float acc_scale_z = 11376.585435;

const int magn_off_x = 2;
const int magn_off_y = -99;
const int magn_off_z = -61;
const float magn_scale_x = 197.907361;
const float magn_scale_y = 208.111457;
const float magn_scale_z = 217.547061;
